<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;

class TbusuarioTableSeeder extends Seeder
{

    /**
     * Auto generated seed file
     *
     * @return void
     */
    public function run()
    {
        

        \DB::table('tbusuario')->delete();
        
\DB::table('tbusuario')->insert(array (
    0 =>
    array (
        'codUsuario' => 1,
        'nomeUsuario' => 'Beatriz Ramos',
        'apelidoUsuario' => 'Bia',
        'biografiaUsuario' => NULL,
        'pronomesUsuario' => NULL,
        'linkUsuario' => NULL,
        'emailUsuario' => 'beatriz.ramos@email.com',
        'telUsuario' => NULL,
        'senhaUsuario' => '$2y$12$pu0e7ncsoYW8bEY9RxTtwe03T.qGW5L.q6hwmAN.xZFd3jWw3bL5G',
        'provedorLoginUsuario' => 'local',
        'googleIdUsuario' => NULL,
        'dataNascimentoUsuario' => '1998-04-22',
        'cidadeUsuario' => 'Sao Paulo',
        'bairroUsuario' => NULL,
        'ufUsuario' => 'SP',
        'fotoPerfilUsuario' => 'perfis/usuarios/1.jpg',
        'temaUsuario' => 'claro',
        'idiomaUsuario' => 'pt-BR',
        'anonimaPadraoUsuario' => 0,
        'statusUsuario' => 'ativa',
        'dataCadastro' => '2026-09-17 18:19:08',
        'dataAtualizacao' => '2026-09-17 18:19:08',
    ),
    1 =>
    array (
        'codUsuario' => 2,
        'nomeUsuario' => 'Mariana Silva',
        'apelidoUsuario' => 'Mari',
        'biografiaUsuario' => 'Gosto de aprender e compartilhar experiencias.',
        'pronomesUsuario' => NULL,
        'linkUsuario' => NULL,
        'emailUsuario' => 'mariana.silva@email.com',
        'telUsuario' => '(11)98888-2345',
        'senhaUsuario' => '$2y$12$pu0e7ncsoYW8bEY9RxTtwe03T.qGW5L.q6hwmAN.xZFd3jWw3bL5G',
        'provedorLoginUsuario' => 'local',
        'googleIdUsuario' => NULL,
        'dataNascimentoUsuario' => '2002-07-15',
        'cidadeUsuario' => 'Sao Paulo',
        'bairroUsuario' => 'Itaquera',
        'ufUsuario' => 'SP',
        'fotoPerfilUsuario' => 'perfis/usuarios/2.jpg',
        'temaUsuario' => 'escuro',
        'idiomaUsuario' => 'pt-BR',
        'anonimaPadraoUsuario' => 1,
        'statusUsuario' => 'ativa',
        'dataCadastro' => '2026-09-18 09:25:14',
        'dataAtualizacao' => '2026-09-18 09:25:14',
    ),
    2 =>
    array (
        'codUsuario' => 3,
        'nomeUsuario' => 'Gabriel Santos',
        'apelidoUsuario' => 'Gabs',
        'biografiaUsuario' => NULL,
        'pronomesUsuario' => 'ele/dele',
        'linkUsuario' => NULL,
        'emailUsuario' => 'gabriel.santos@email.com',
        'telUsuario' => NULL,
        'senhaUsuario' => '$2y$12$pu0e7ncsoYW8bEY9RxTtwe03T.qGW5L.q6hwmAN.xZFd3jWw3bL5G',
        'provedorLoginUsuario' => 'local',
        'googleIdUsuario' => NULL,
        'dataNascimentoUsuario' => '2000-11-03',
        'cidadeUsuario' => 'Guarulhos',
        'bairroUsuario' => NULL,
        'ufUsuario' => 'SP',
        'fotoPerfilUsuario' => 'perfis/usuarios/3.jpg',
        'temaUsuario' => 'claro',
        'idiomaUsuario' => 'pt-BR',
        'anonimaPadraoUsuario' => 0,
        'statusUsuario' => 'ativa',
        'dataCadastro' => '2026-09-18 14:42:33',
        'dataAtualizacao' => '2026-09-18 14:42:33',
    ),
    3 =>
    array (
        'codUsuario' => 4,
        'nomeUsuario' => 'Ana Clara Oliveira',
        'apelidoUsuario' => 'Aninha',
        'biografiaUsuario' => 'Buscando informacoes e conhecimento.',
        'pronomesUsuario' => 'ela/dela',
        'linkUsuario' => NULL,
        'emailUsuario' => 'ana.oliveira@email.com',
        'telUsuario' => '(11)97777-4567',
        'senhaUsuario' => '$2y$12$pu0e7ncsoYW8bEY9RxTtwe03T.qGW5L.q6hwmAN.xZFd3jWw3bL5G',
        'provedorLoginUsuario' => 'local',
        'googleIdUsuario' => NULL,
        'dataNascimentoUsuario' => '2003-02-18',
        'cidadeUsuario' => 'Sao Paulo',
        'bairroUsuario' => 'Guaianazes',
        'ufUsuario' => 'SP',
        'fotoPerfilUsuario' => 'perfis/usuarios/4.jpg',
        'temaUsuario' => 'escuro',
        'idiomaUsuario' => 'pt-BR',
        'anonimaPadraoUsuario' => 0,
        'statusUsuario' => 'ativa',
        'dataCadastro' => '2026-09-19 10:15:27',
        'dataAtualizacao' => '2026-09-19 10:15:27',
    ),
    4 =>
    array (
        'codUsuario' => 5,
        'nomeUsuario' => 'Lucas Ferreira',
        'apelidoUsuario' => 'Luquinhas',
        'biografiaUsuario' => NULL,
        'pronomesUsuario' => NULL,
        'linkUsuario' => NULL,
        'emailUsuario' => 'lucas.ferreira@email.com',
        'telUsuario' => NULL,
        'senhaUsuario' => '$2y$12$pu0e7ncsoYW8bEY9RxTtwe03T.qGW5L.q6hwmAN.xZFd3jWw3bL5G',
        'provedorLoginUsuario' => 'local',
        'googleIdUsuario' => NULL,
        'dataNascimentoUsuario' => '1999-09-27',
        'cidadeUsuario' => 'Osasco',
        'bairroUsuario' => NULL,
        'ufUsuario' => 'SP',
        'fotoPerfilUsuario' => 'perfis/usuarios/5.jpg',
        'temaUsuario' => 'claro',
        'idiomaUsuario' => 'pt-BR',
        'anonimaPadraoUsuario' => 1,
        'statusUsuario' => 'inativa',
        'dataCadastro' => '2026-09-19 16:38:49',
        'dataAtualizacao' => '2026-09-19 16:38:49',
    ),
    5 =>
    array (
        'codUsuario' => 6,
        'nomeUsuario' => 'Julia Martins',
        'apelidoUsuario' => 'Ju',
        'biografiaUsuario' => 'Adoro ajudar e aprender com outras pessoas.',
        'pronomesUsuario' => 'ela/dela',
        'linkUsuario' => NULL,
        'emailUsuario' => 'julia.martins@email.com',
        'telUsuario' => '(11)96666-5678',
        'senhaUsuario' => '$2y$12$pu0e7ncsoYW8bEY9RxTtwe03T.qGW5L.q6hwmAN.xZFd3jWw3bL5G',
        'provedorLoginUsuario' => 'local',
        'googleIdUsuario' => NULL,
        'dataNascimentoUsuario' => '2001-12-09',
        'cidadeUsuario' => 'Sao Paulo',
        'bairroUsuario' => 'Penha',
        'ufUsuario' => 'SP',
        'fotoPerfilUsuario' => 'perfis/usuarios/6.jpg',
        'temaUsuario' => 'escuro',
        'idiomaUsuario' => 'pt-BR',
        'anonimaPadraoUsuario' => 0,
        'statusUsuario' => 'ativa',
        'dataCadastro' => '2026-09-20 11:22:05',
        'dataAtualizacao' => '2026-09-20 11:22:05',
    ),
    6 =>
    array (
        'codUsuario' => 7,
        'nomeUsuario' => 'Rafael Costa',
        'apelidoUsuario' => 'Rafa',
        'biografiaUsuario' => NULL,
        'pronomesUsuario' => 'ele/dele',
        'linkUsuario' => NULL,
        'emailUsuario' => 'rafael.costa@email.com',
        'telUsuario' => NULL,
        'senhaUsuario' => '$2y$12$pu0e7ncsoYW8bEY9RxTtwe03T.qGW5L.q6hwmAN.xZFd3jWw3bL5G',
        'provedorLoginUsuario' => 'local',
        'googleIdUsuario' => NULL,
        'dataNascimentoUsuario' => '1997-06-12',
        'cidadeUsuario' => 'Santo Andre',
        'bairroUsuario' => NULL,
        'ufUsuario' => 'SP',
        'fotoPerfilUsuario' => 'perfis/usuarios/7.jpg',
        'temaUsuario' => 'claro',
        'idiomaUsuario' => 'pt-BR',
        'anonimaPadraoUsuario' => 1,
        'statusUsuario' => 'ativa',
        'dataCadastro' => '2026-09-20 15:40:18',
        'dataAtualizacao' => '2026-09-20 15:40:18',
    ),
    7 =>
    array (
        'codUsuario' => 8,
        'nomeUsuario' => 'Camila Rodrigues',
        'apelidoUsuario' => 'Cami',
        'biografiaUsuario' => 'Interessada em saude, tecnologia e educacao.',
        'pronomesUsuario' => 'ela/dela',
        'linkUsuario' => NULL,
        'emailUsuario' => 'camila.rodrigues@email.com',
        'telUsuario' => '(11)95555-6789',
        'senhaUsuario' => '$2y$12$pu0e7ncsoYW8bEY9RxTtwe03T.qGW5L.q6hwmAN.xZFd3jWw3bL5G',
        'provedorLoginUsuario' => 'local',
        'googleIdUsuario' => NULL,
        'dataNascimentoUsuario' => '2004-03-25',
        'cidadeUsuario' => 'Sao Paulo',
        'bairroUsuario' => 'Vila Prudente',
        'ufUsuario' => 'SP',
        'fotoPerfilUsuario' => 'perfis/usuarios/8.jpg',
        'temaUsuario' => 'escuro',
        'idiomaUsuario' => 'pt-BR',
        'anonimaPadraoUsuario' => 0,
        'statusUsuario' => 'ativa',
        'dataCadastro' => '2026-09-20 18:05:42',
        'dataAtualizacao' => '2026-09-20 18:05:42',
    ),
));
        
        
    }
}